language: python

python:
    - "2.6"
    - "2.7"
    - "3.3"

env:
    - DJANGO=1.7.7
    - DJANGO=1.7.6
    - DJANGO=1.7.5
    - DJANGO=1.7.4
    - DJANGO=1.7.3
    - DJANGO=1.6.11
    - DJANGO=1.6.10
    - DJANGO=1.6.9
    - DJANGO=1.6.8
    - DJANGO=1.6.7

matrix:
    exclude:
        - python: "2.6"
        env: DJANGO=1.7.7
        - python: "2.6"
        env: DJANGO=1.7.6
        - python: "2.6"
        env: DJANGO=1.7.5
        - python: "2.6"
        env: DJANGO=1.7.4
        - python: "2.6"
        env: DJANGO=1.7.3

install:
    - pip install Django==$DJANGO
    - pip install -e .

script:
    - python run_tests.py

notifications:
    email:
        recipients:
          - jon@faustman.org
        on_success: never
        on_failure: always
